### ISSUE TITLE
NullPointerException in DriverHomeActivity

### ISSUE THREAD

**Issue by DulongSang** [CMPUT301W20T29-H03/ZoomWroom#190]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.example.zoomwroom.Entities.DriveRequest.getRiderID()' on a null object reference
        at com.example.zoomwroom.DriverHomeActivity.showDriveRequestFragment(DriverHomeActivity.java:324)
        at com.example.zoomwroom.DriverHomeActivity.onMarkerClick(DriverHomeActivity.java:292)
```

**Comment by DulongSang** [comment]
happened when I clicked a marker on the map, I think it is a destination or pickup location marker for a particular DriveRequest.

**Comment by DulongSang** [comment]
and after this crash, the app kept crashing until I reinstall the app.
The error message is different from the above
```
com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
        at com.google.maps.api.android.lib6.common.m.b(:com.google.android.gms.dynamite_mapsdynamite@200914084@20.09.14 (120700-0):6)
        at com.google.maps.api.android.lib6.gmm6.api.c.a(:com.google.android.gms.dynamite_mapsdynamite@200914084@20.09.14 (120700-0):36)
        at com.google.maps.api.android.lib6.impl.y.a(:com.google.android.gms.dynamite_mapsdynamite@200914084@20.09.14 (120700-0):0)
        at com.google.maps.api.android.lib6.gmm6.api.c.a(:com.google.android.gms.dynamite_mapsdynamite@200914084@20.09.14 (120700-0):47)
        at com.google.maps.api.android.lib6.impl.bi.a(:com.google.android.gms.dynamite_mapsdynamite@200914084@20.09.14 (120700-0):250)
        at com.google.android.gms.maps.internal.i.a(:com.google.android.gms.dynamite_mapsdynamite@200914084@20.09.14 (120700-0):174)
        at ch.onTransact(:com.google.android.gms.dynamite_mapsdynamite@200914084@20.09.14 (120700-0):4)
        at android.os.Binder.transact(Binder.java:914)
        at com.google.android.gms.internal.maps.zza.zzb(Unknown Source:20)
        at com.google.android.gms.maps.internal.zzg.moveCamera(Unknown Source:20)
        at com.google.android.gms.maps.GoogleMap.moveCamera(Unknown Source:13)
        at com.example.zoomwroom.DriverHomeActivity.checkOngoing(DriverHomeActivity.java:272)
        at com.example.zoomwroom.DriverHomeActivity.getLastLocation(DriverHomeActivity.java:252)
        at com.example.zoomwroom.MapsActivity.onMapReady(MapsActivity.java:125)
        at com.example.zoomwroom.DriverHomeActivity.onMapReady(DriverHomeActivity.java:230)
```

**Comment by heyitshenrylin** [comment]
Seems like the particular driverequest isnt actually there anymore, try tapping on the map to refresh the marker list

**Comment by heyitshenrylin** [comment]
Also, adding frequent checks to see whether destinationMarker != null or ongoingRequest != null should fix this
